function TermsOfService() {
  return (
    <div style={{ fontFamily: "Georgia, serif", maxWidth: "720px", margin: "0 auto", padding: "48px 24px", color: "#1a1a1a" }}>
      <h1 style={{ fontSize: "28px", fontWeight: "700", marginBottom: "8px" }}>Terms of Service</h1>
      <p style={{ color: "#888", fontFamily: "sans-serif", fontSize: "13px", marginBottom: "40px" }}>Last updated: July 2026</p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>1. Acceptance of Terms</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        By accessing or using Nouri ("the Service") at trynouri.app, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>2. Description of Service</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        Nouri is an AI-powered recipe generation tool that provides personalized recipe suggestions based on user inputs. The Service is provided for informational and personal use only. Recipes generated by the Service are not a substitute for professional nutritional or medical advice.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>3. AI-Generated Content</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        Recipes and nutritional information provided by Nouri are generated by artificial intelligence and are for general informational purposes only. While we strive for accuracy, we make no guarantees regarding the nutritional accuracy, safety, or suitability of any recipe for your individual dietary needs. Always consult a qualified nutritionist or healthcare professional before making significant dietary changes.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>4. User Responsibilities</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to use the Service to submit any harmful, offensive, or inappropriate content. You are solely responsible for the inputs you provide and how you use the generated content.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>5. Intellectual Property</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        The Nouri name, logo, and all associated branding are the property of Nouri. AI-generated recipes produced through your use of the Service may be used by you for personal, non-commercial purposes. You may not reproduce, distribute, or sell content from the Service without prior written permission.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>6. Disclaimer of Warranties</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. Nouri does not warrant that the Service will be uninterrupted, error-free, or free of harmful components. We disclaim all warranties, including implied warranties of merchantability and fitness for a particular purpose.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>7. Limitation of Liability</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        To the fullest extent permitted by law, Nouri shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to health issues arising from recipes generated by the Service.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>8. Dispute Resolution — ICC Arbitration</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        Any dispute, controversy, or claim arising out of or relating to these Terms of Service, or the breach, termination, or invalidity thereof, shall be finally settled by arbitration in accordance with the Rules of Arbitration of the International Chamber of Commerce (ICC) by one or more arbitrators appointed in accordance with the said Rules. The seat of arbitration shall be New York, New York. The language of the arbitration shall be English. The arbitral award shall be final and binding upon both parties, and judgment upon the award may be entered in any court having jurisdiction thereof. Nothing in this clause shall prevent either party from seeking emergency injunctive relief in a court of competent jurisdiction where necessary to prevent irreparable harm.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>9. Governing Law</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        These Terms shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of law provisions.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>10. Changes to Terms</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated date. Your continued use of the Service after changes are posted constitutes your acceptance of the revised Terms.
      </p>

      <h2 style={{ fontSize: "16px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "8px" }}>11. Contact</h2>
      <p style={{ lineHeight: "1.8", color: "#444", marginBottom: "32px" }}>
        If you have any questions about these Terms, please contact us at support@trynouri.app.
      </p>

      <a href="/" style={{ fontFamily: "sans-serif", fontSize: "13px", color: "#888", textDecoration: "none" }}>← Back to Nouri</a>
    </div>
  );
}

export default TermsOfService;
